CREATE TABLE IF NOT EXISTS reviews (
    id VARCHAR PRIMARY KEY,
    author VARCHAR NOT NULL,
    store VARCHAR NOT NULL,
    text VARCHAR NOT NULL,
    rating INT NOT NULL,
    latency_ms DOUBLE PRECISION
);
